name: Push

on:
  workflow_call:
    inputs:
        rocks:
            description: List of rocks to build
            required: true
            type: string
            default: '[]'
        publish:
            description: Publish rocks ?
            default: false
            type: boolean

jobs:

  build:
    name: Build rock
    strategy:
      fail-fast: false
      matrix:
        rock: ${{ fromJson(inputs.rocks) }}
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v49.0.3
    with:
      path-to-rock-directory: rocks/${{ matrix.rock }}
      artifact-prefix: packed-rock-${{ matrix.rock }}
    permissions:
      actions: read  # Needed by build_rock.yaml to look up the workflow version
      contents: read

  publish:
    if: ${{ inputs.publish }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        rock: ${{ fromJson(inputs.rocks) }}
    uses: canonical/data-platform-workflows/.github/workflows/release_rock_edge.yaml@v49.0.3
    with:
      path-to-rock-directory: rocks/${{ matrix.rock }}
      artifact-prefix: packed-rock-${{ matrix.rock }}
    permissions:
      actions: read  # Needed by release_rock_edge.yaml to look up the workflow version
      contents: write  # Needed by release_rock_edge.yaml
      packages: write  # Needed to publish to GitHub Container Registry
